Esmerealda-inventario/Desarrollo.Inventario/Desarrollo.Inventario/Controllers/AdminController.cs
using Desarrollo.Inventario.WebAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ch2018.WebAdmin.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin

      


        public ActionResult Autenticar(LoginVM login)
        {
           string  usuario = System.Configuration.ConfigurationManager.AppSettings["usuario"];
            string clave= System.Configuration.ConfigurationManager.AppSettings["clave"];


            if (usuario == login.usuario && login.clave == clave)
            {

              System.Web.Security.FormsAuthentication.SetAuthCookie(login.usuario, false);
              return RedirectToAction("Index");

                
            }
            else
            {
                TempData["credenciales"] = "0";
               return  RedirectToAction("Index", "Home");
            }
        }


        [Authorize]
        public ActionResult Logout(LoginVM datos)
        {
            if (System.Web.HttpContext.Current.Request.IsAuthenticated)
            {
                System.Web.Security.FormsAuthentication.SignOut();
            }
            return RedirectToAction("Index","Home");
        }


        [Authorize]
        public ActionResult index()
        {


            return View();
        }

      


    }
}

Esmerealda-inventario/Desarrollo.Inventario/Desarrollo.Inventario/Controllers/CategoriaController.cs
using Desarrollo.Inventario.ModelosBASE;
using Desarrollo.Inventario.Models.CategoriasModel;
using Desarrollo.Inventario.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Westwind.Web.Mvc;

namespace Desarrollo.Inventario.Controllers
{
    public class CategoriaController : Controller
    {
        CategoriaService _CategoriaService = new CategoriaService();


        [Authorize]
        public ActionResult Listado(CategoriaListaVM listadocat)
        {
            
            List<Categoria> Categorias = _CategoriaService.ListadoCategorias(listadocat.codigo,listadocat.nombre);

            CategoriaListaVM objcat = new CategoriaListaVM()
            {
                codigo=listadocat.codigo,
                listadoCategorias= Categorias,
                 nombre=listadocat.nombre
                
               
            };
          

            return View(objcat);
        }

        [Authorize]
        public JsonResult GuardarCategoria(string nombre,string detalles)
        {
            bool exito = _CategoriaService.GuardarCategoria(nombre, detalles);

            List<Categoria> Categorias = _CategoriaService.ListadoCategorias(null,"");

            CategoriaListaVM objcat = new CategoriaListaVM()
            {
                listadoCategorias = Categorias,
               
            };
           
            string postsHtml = ViewRenderer.RenderPartialView("~/Views/Categoria/_listadoCategorias.cshtml", objcat);

            return Json(new { exito = exito, postsHtml = postsHtml }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult EliminarCategoria(int idcategoria)
        {
            int resultado = _CategoriaService.EliminarCategoria(idcategoria);
            
            return Json(new { exito = resultado }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult GetCategoria(int codigo)
        {

            Categoria cataActual = _CategoriaService.GetCategoria(codigo);


            return Json(new { codigo = cataActual.codigo_categoria, cat = cataActual.categoria1, detalle = cataActual.detalles });

        }




        [Authorize]
        public JsonResult Editarcategoria(int codigo,string nombre, string detalles)
        {
            bool exito = _CategoriaService.ActualizarCategoria(codigo,nombre, detalles);

            List<Categoria> Categorias = _CategoriaService.ListadoCategorias(null, "");

            CategoriaListaVM objcat = new CategoriaListaVM()
            {
                listadoCategorias = Categorias,

            };

            string postsHtml = ViewRenderer.RenderPartialView("~/Views/Categoria/_listadoCategorias.cshtml", objcat);

            return Json(new { exito = true, postsHtml = postsHtml }, JsonRequestBehavior.AllowGet);
        }

    }
}

Esmerealda-inventario/Desarrollo.Inventario/Desarrollo.Inventario/Controllers/ProveedoresController.cs
using Desarrollo.Inventario.ModelosBASE;
using Desarrollo.Inventario.Models.ProveedoresModel;
using Desarrollo.Inventario.Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Westwind.Web.Mvc;

namespace Desarrollo.Inventario.Controllers
{
    public class ProveedoresController : Controller
    {
        ProveedoresService proveedoresService = new ProveedoresService();

       
        [Authorize]
        
        public ActionResult Index(proveedoresListVM _proveedoresListVM)
        {
            proveedoresListVM objproveedores = new proveedoresListVM() {
                    codigo= _proveedoresListVM.codigo,
                    nombre = _proveedoresListVM.nombre,
                    listadoproveedores=proveedoresService.listadoproveedores(_proveedoresListVM.codigo, _proveedoresListVM.nombre)

            };



            return View(objproveedores);
        }


        [Authorize]
        public JsonResult GuardarProveedor(string nombre, string direccion, string telefono, string correo)
        {
            bool exito = proveedoresService.GuardarProveedor(nombre, direccion, telefono, correo);

            List<Proveedores> proveedor = proveedoresService.listadoproveedores(null, "");

            proveedoresListVM objcat = new proveedoresListVM()
            {
                listadoproveedores = proveedor,

            };

            string postsHtml = ViewRenderer.RenderPartialView("~/Views/Proveedores/listadoProveedores.cshtml", objcat);

            return Json(new { exito = exito, postsHtml = postsHtml }, JsonRequestBehavior.AllowGet);
        }








    }
}

Esmerealda-inventario/Desarrollo.Inventario/Desarrollo.Inventario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>InventarioUtec - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/plugins")
    @Styles.Render("~/css/bitworkstyles")
    @* @Styles.Render("~/bundles/bitlibs/ventanas/bitframeworkstyles")*@

</head>
<body>
    <div id="wrapper">

        <!-- Contenedor Principal Izquierdo -->
        <nav class="navbar-default navbar-static-side">
            <div class="sidebar-collapse">

                <ul class="nav metismenu" id="side-menu">

                    <!-- Logo + Titulo del Sistema -->
                    <li class="nav-header">
                        <div class="profile-element">

                            <!-- Logo cuando el panel esta completo -->
                            <div class="logo">
                                <img src="~/img/logo.png" />
                            </div>
                            <h4></h4>
                        </div>

                        <!-- Logo cuando el panel esta minimizado -->
                        <div class="logo-element">
                            <img src="~/img/logo-icon.png" />
                        </div>
                    </li>

                    <!-- Menú Principal / Lista de items -->
                    <!-- Para mostrar el item del menú activo, solo es necesario agregar la clase active al li -->
                    <!-- Para mostrar un submenu es recomendable mostrar un icono de flecha a la derecha, por lo que se agrega un tag <span class="fa arrow"></span> dentro del tag <a> -->
                    <!-- Para mostrar un icono al lado del texto, es necesario usar el tag <i> seguido de la clase fa + la clase del icono a mostrar.
    Estos iconos son vectores, la cual son sacados de la tipografia Font Awsome - https://fortawesome.github.io/Font-Awesome/icons/ -->
                    <!-- Helper para Menu del Nuevo Diseño  -->
                    @*@Html.menuNuevoFormato((string)ViewBag.mnuEncabezado, (int)ViewBag.mnuRootSubMenu, (int)ViewBag.mnuMenuActivo)*@


                    <li class="active">
                        <a href="#"><i class="fa fa-file-text"></i> <span class="nav-label">Proveedores</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="@Url.Action("Index","Proveedores")">Listado de Proveedores</a></li>

                        </ul>
                    </li>


                    <li class="active">
                        <a href="#"><i class="fa fa-file-text"></i> <span class="nav-label">Categorias</span> <span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a href="@Url.Action("Listado","Categoria")">Listado de Categorias</a></li>

                        </ul>
                    </li>

                    <!-- ---------------------------  -->
                    <!--  Nuevo Menus Para el diseño  -->
                    @*<li class="active">
            <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Item 1</span> <span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
                <li><a href="#">Item 1.1</a></li>
                <li><a href="#">Item 1.2</a></li>
                <li><a href="#">Item 1.3</a></li>
                <li class="active"><a href="#">Item 1.4</a></li>
                <li><a href="#">Item 1.5 <span class="label label-primary pull-right">NUEVO</span></a></li>
            </ul>
        </li>
        <li>
            <a href="#"><i class="fa fa-diamond"></i> <span class="nav-label">Item 2</span> <span class="label label-warning pull-right">16/24</span></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-sitemap"></i> <span class="nav-label">Menu Levels </span><span class="fa arrow"></span></a>
            <ul class="nav nav-second-level collapse">
                <li>
                    <a href="#">Third Level <span class="fa arrow"></span></a>
                    <ul class="nav nav-third-level">
                        <li><a href="#">Third Level Item</a></li>
                        <li><a href="#">Third Level Item</a></li>
                        <li><a href="#">Third Level Item</a></li>
                    </ul>
                </li>
                <li><a href="#">Second Level Item</a></li>
                <li><a href="#">Second Level Item</a></li>
                <li><a href="#">Second Level Item</a></li>
            </ul>
        </li>
        <li>
            <a href="#"><i class="fa fa-envelope"></i> <span class="nav-label">Item 3</span></a>
        </li>*@

                </ul>
            </div>
        </nav>

        <!-- Contenedor Principal - Navegacion superior, Header titulos, Contenido, Footer -->
        <div id="page-wrapper" class="gray-bg">

            <!-- Navegación superior -->
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">

                    <!-- Botón para minimizar panel izquierdo + Barra de búsqueda -->
                    <div class="navbar-header">

                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href="#"><i class="fa fa-bars"></i></a>

                        @*<form role="search" class="navbar-form-custom">
                                <div class="form-group">
                                    <input type="text" placeholder="Buscar..." class="form-control" name="top-search" id="top-search">
                                </div>
                            </form>*@


                    </div>
                    <!-- -->
                    <!-- Lista de items -->
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <span class="m-r-sm text-muted welcome-message">

                            </span>
                        </li>
                    
                        <li>
                            <a href="@Url.Action("Logout", "Admin")">
                                <i class="fa fa-sign-out"></i> Log out
                            </a>
                        </li>
                    </ul>
                    <!-- -->

                </nav>
            </div>
            <!-- -->
            <!-- Contenido de la views-->
            @RenderBody()
            <!-- -->
            <!-- Modal Forms -->

            <div class="modal inmodal fade" id="modal-forms" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-md" id="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="modal-title"></h4>
                        </div>
                        <div id="modal-content">
                        </div>
                    </div>
                </div>
            </div>


            <!-- Footer -->
            <div class="footer">
                <div class="pull-right">
                    InventarioUtec &copy; @DateTime.Now.Year
                </div>
                <div>
                    <strong>InventarioUtec</strong>
                </div>
            </div>
            <!-- -->


        </div>

    </div>


    @Scripts.Render("~/bundles/Layaot")
    @Scripts.Render("~/bundles/Plugins")
    @Scripts.Render("~/bundles/jqval")
    @Scripts.Render("~/bundles/bitlibs")

    @RenderSection("scripts", required: false)

</body>
</html>